export const ar = {
  /* نفس المحتوى الأصلي */
  appName: "منصة السلامة والصحة المهنية",
  appSub: "EHS Platform",
  dashboard: "لوحة التحكم",
  permits: "تصاريح العمل",
  fieldNotes: "الملاحظات الميدانية",
  incidents: "الحوادث",
  tbt: "التدريب اليومي",
  licenses: "الرخص والشهادات",
  reports: "التقارير",
  settings: "الإعدادات",
  logout: "تسجيل الخروج",
  login: "تسجيل الدخول",
  username: "رقم الهوية",
  password: "كلمة المرور",
  loginBtn: "دخول",
  invalidLogin: "رقم الهوية أو كلمة المرور غير صحيحة",
  testAccounts: "حسابات تجريبية",
  allProjects: "جميع المشاريع",
  activePermits: "التصاريح النشطة",
  notesClose: "نسبة إغلاق الملاحظات",
  daysNoIncident: "أيام بدون حوادث",
  trainingAttend: "نسبة حضور التدريب",
  addNew: "إضافة جديد",
  edit: "تعديل",
  delete: "حذف",
  view: "عرض",
  save: "حفظ",
  cancel: "إلغاء",
  confirmDelete: "تأكيد الحذف",
  confirmDeleteMsg: "هل أنت متأكد من حذف هذا العنصر؟ لا يمكن التراجع.",
  yes: "نعم، احذف",
  no: "إلغاء",
  type: "النوع",
  project: "المشروع",
  location: "الموقع",
  supervisor: "المشرف",
  date: "التاريخ",
  description: "الوصف",
  status: "الحالة",
  severity: "مستوى الخطورة",
  active: "نشط",
  closed: "مغلق",
  hot: "أعمال حارة",
  cold: "أعمال باردة",
  confined: "أماكن مغلقة",
  heights: "أعمال ارتفاعات",
  electrical: "أعمال كهربائية",
  unsafeAct: "تصرف غير آمن",
  unsafeCondition: "حالة غير آمنة",
  critical: "حرجة",
  high: "عالية",
  medium: "متوسطة",
  low: "منخفضة",
  injury: "إصابة",
  electrical2: "كهرباء",
  slip: "انزلاق",
  fall: "سقوط",
  fire: "حريق",
  suffocation: "اختناق",
  injured: "اسم المصاب",
  action: "الإجراء المتخذ",
  title: "العنوان",
  topic: "الموضوع",
  time: "الوقت",
  trainer: "المدرب",
  attendees: "عدد الحضور",
  attendRate: "نسبة الحضور",
  issueDate: "تاريخ الإصدار",
  expiry: "تاريخ الانتهاء",
  valid: "صالحة",
  expired: "منتهية",
  expiring: "قاربت الانتهاء",
  name: "الاسم",
  safetyManager: "مدير السلامة",
  safetySupervisor: "مراقب السلامة",
  unauthorized: "غير مصرح",
  unauthorizedMsg: "ليس لديك صلاحية للوصول إلى هذه الصفحة",
  backHome: "العودة للرئيسية",
  recentPermits: "آخر التصاريح",
  recentIncidents: "آخر الحوادث",
  fieldNotesChart: "ملخص الملاحظات الميدانية",
  unsafeActCount: "تصرف غير آمن",
  unsafeCondCount: "حالة غير آمنة",
  exportPDF: "تصدير PDF",
  exportExcel: "تصدير Excel",
  reportExported: "تم تصدير التقرير بنجاح",
  totalPermits: "إجمالي التصاريح",
  totalNotes: "إجمالي الملاحظات",
  totalIncidents: "إجمالي الحوادث",
  totalTBT: "إجمالي جلسات التدريب",
  totalLicenses: "إجمالي الرخص",
  notFound: "العنصر غير موجود أو غير مصرح بالوصول إليه",
  language: "اللغة",
  theme: "المظهر",
  darkMode: "الوضع الليلي",
  arabicLang: "العربية",
  englishLang: "English",
  changePassword: "تغيير كلمة المرور",
  currentPass: "كلمة المرور الحالية",
  newPass: "كلمة المرور الجديدة",
  confirmPass: "تأكيد كلمة المرور",
  saved: "تم الحفظ بنجاح",
  deleted: "تم الحذف بنجاح",
  added: "تم الإضافة بنجاح",
  updated: "تم التحديث بنجاح",
  required: "هذا الحقل مطلوب",
  detailedLocation: "الموقع التفصيلي",
  myProject: "مشروعي",
  attendanceRate: "نسبة الحضور",
  noData: "لا توجد بيانات",
  fieldRequired: "الحقول المطلوبة",
  incidentType: "نوع الحادث",
  pageTitle: "",
  permitsManagement: "إدارة التصاريح",
  notesManagement: "إدارة الملاحظات",
  incidentsManagement: "إدارة الحوادث",
  tbtManagement: "إدارة التدريب",
  licensesManagement: "إدارة الرخص",
  reportsView: "عرض التقارير",
  settingsPage: "الإعدادات",
  details: "التفاصيل",
  back: "رجوع",
  allTypes: "كل الأنواع",
  allProj: "كل المشاريع",
  allStatus: "كل الحالات",
  allSev: "كل المستويات",
  search: "بحث...",
  addNote: "إضافة ملاحظة",
  addPermit: "إضافة تصريح عمل",
  addIncident: "إضافة حادث",
  addTBT: "إضافة جلسة تدريب",
  addLicense: "إضافة رخصة",
  permitDetails: "تفاصيل التصريح",
  noteDetails: "تفاصيل الملاحظة",
  incidentDetails: "تفاصيل الحادث",
  tbtDetails: "تفاصيل جلسة التدريب",
  licenseDetails: "تفاصيل الرخصة",
  projectsOverview: "نظرة عامة على المشاريع",
  safetyIndicators: "مؤشرات السلامة",
  incidentsByType: "الحوادث حسب النوع",
  permitsStatus: "حالة التصاريح",
  notesStats: "إحصائيات الملاحظات",
  welcomeMsg: "مرحباً",
  projectAirport: "مشروع المطار - الرياض",
  projectMedical: "مشروع المدينة الطبية - الدمام",
  projectResidential: "مشروع المجمع السكني - جدة",
  loading: "جاري تحميل البيانات......",
  itemNotFound: "العنصر غير موجود",
  error: "خطأ",
  open: "مفتوح",
  manageProjects: "إدارة المشاريع",
  addProject: "إضافة مشروع",
  key: "المفتاح",
  nameAr: "الاسم (عربي)",
  nameEn: "الاسم (إنجليزي)",
  manageSupervisors: "إدارة المراقبين",
  addSupervisor: "إضافة مراقب",
  editSupervisor: "تعديل مراقب",
  passwordRequired: "كلمة المرور مطلوبة",
  leaveBlankToKeep: "اتركه فارغاً للاحتفاظ بكلمة المرور الحالية",
  passwordMismatch: "كلمتا المرور غير متطابقتين",
  deleteProjectConfirm: "هل أنت متأكد من حذف مشروع",
  deleteSupervisorConfirm: "هل أنت متأكد من حذف المراقب",
  projectsAndSupervisors: "المشاريع والمراقبين",
  editPermit: "تعديل التصريح",
  closingNotesRate: "نسبة إغلاق الملاحظات",
  noDescription: "لا يوجد وصف",
  noteTitle: "عنوان الملاحظة",
  noteDescription: "وصف الملاحظة",
  incidentsTitle: "عنوان الحادث",
  incidentsLocation: "موقع الحادث",
  incidentsSupervisor: "اسم المصاب",
  actionTaken: "الإجراء المتخذ",
  allSeverity: "كل مستويات الخطورة",
  editIncident: "تعديل حادث",
  addIncident: "إضافة حادث",
  exportOptions: "خيارات التصدير",
  selectProjectForExport: "اختر المشروع المراد تصديره",
  exportTypeNote: "سيتم التصدير بصيغة",
  export: "تصدير",
  print: "طباعة",
  allTime: "كل الأوقات",
  daily: "يومي",
  weekly: "أسبوعي",
  monthly: "شهري",
  yearly: "سنوي",
};
