export const en = {
  appName: "EHS Platform",
  appSub: "Safety & Health Management",
  dashboard: "Dashboard",
  permits: "Work Permits",
  fieldNotes: "Field Notes",
  incidents: "Incidents",
  tbt: "Toolbox Talk",
  licenses: "Licenses",
  reports: "Reports",
  settings: "Settings",
  logout: "Logout",
  login: "Login",
  username: "ID Number",
  password: "Password",
  loginBtn: "Sign In",
  invalidLogin: "Invalid ID or password",
  testAccounts: "Test Accounts",
  allProjects: "All Projects",
  activePermits: "Active Permits",
  notesClose: "Notes Closure Rate",
  daysNoIncident: "Days Without Incidents",
  trainingAttend: "Training Attendance",
  addNew: "Add New",
  edit: "Edit",
  delete: "Delete",
  view: "View",
  save: "Save",
  cancel: "Cancel",
  confirmDelete: "Confirm Delete",
  confirmDeleteMsg:
    "Are you sure you want to delete this item? This cannot be undone.",
  yes: "Yes, Delete",
  no: "Cancel",
  type: "Type",
  project: "Project",
  location: "Location",
  supervisor: "Supervisor",
  date: "Date",
  description: "Description",
  status: "Status",
  severity: "Severity",
  active: "Active",
  closed: "Closed",
  hot: "Hot Work",
  cold: "Cold Work",
  confined: "Confined Space",
  heights: "Work at Heights",
  electrical: "Electrical Work",
  unsafeAct: "Unsafe Act",
  unsafeCondition: "Unsafe Condition",
  critical: "Critical",
  high: "High",
  medium: "Medium",
  low: "Low",
  injury: "Injury",
  electrical2: "Electrical",
  slip: "Slip",
  fall: "Fall",
  fire: "Fire",
  suffocation: "Suffocation",
  injured: "Injured Person",
  action: "Action Taken",
  title: "Title",
  topic: "Topic",
  time: "Time",
  trainer: "Trainer",
  attendees: "Attendees",
  attendRate: "Attendance Rate",
  issueDate: "Issue Date",
  expiry: "Expiry Date",
  valid: "Valid",
  expired: "Expired",
  expiring: "Expiring Soon",
  name: "Name",
  safetyManager: "Safety Manager",
  safetySupervisor: "Safety Supervisor",
  unauthorized: "Unauthorized",
  unauthorizedMsg: "You do not have permission to access this page.",
  backHome: "Back to Home",
  recentPermits: "Recent Permits",
  recentIncidents: "Recent Incidents",
  fieldNotesChart: "Field Notes Summary",
  unsafeActCount: "Unsafe Act",
  unsafeCondCount: "Unsafe Condition",
  exportPDF: "Export PDF",
  exportExcel: "Export Excel",
  reportExported: "Report exported successfully",
  totalPermits: "Total Permits",
  totalNotes: "Total Notes",
  totalIncidents: "Total Incidents",
  totalTBT: "Total TBT Sessions",
  totalLicenses: "Total Licenses",
  notFound: "Item not found or access denied",
  language: "Language",
  theme: "Theme",
  darkMode: "Dark Mode",
  arabicLang: "العربية",
  englishLang: "English",
  changePassword: "Change Password",
  currentPass: "Current Password",
  newPass: "New Password",
  confirmPass: "Confirm Password",
  saved: "Saved successfully",
  deleted: "Deleted successfully",
  added: "Added successfully",
  updated: "Updated successfully",
  required: "This field is required",
  detailedLocation: "Detailed Location",
  myProject: "My Project",
  attendanceRate: "Attendance Rate",
  noData: "No data available",
  fieldRequired: "Required fields",
  incidentType: "Incident Type",
  permitsManagement: "Permits Management",
  notesManagement: "Notes Management",
  incidentsManagement: "Incidents Management",
  tbtManagement: "TBT Management",
  licensesManagement: "Licenses Management",
  reportsView: "Reports",
  settingsPage: "Settings",
  details: "Details",
  back: "Back",
  allTypes: "All Types",
  allProj: "All Projects",
  allStatus: "All Status",
  allSev: "All Severities",
  search: "Search...",
  addNote: "Add Note",
  addPermit: "Add Permit",
  addIncident: "Add Incident",
  addTBT: "Add Session",
  addLicense: "Add License",
  permitDetails: "Permit Details",
  noteDetails: "Note Details",
  incidentDetails: "Incident Details",
  tbtDetails: "TBT Session Details",
  licenseDetails: "License Details",
  projectsOverview: "Projects Overview",
  safetyIndicators: "Safety Indicators",
  incidentsByType: "Incidents by Type",
  permitsStatus: "Permits Status",
  notesStats: "Notes Statistics",
  welcomeMsg: "Welcome",
  projectAirport: "Airport Project - Riyadh",
  projectMedical: "Medical City Project - Dammam",
  projectResidential: "Residential Complex - Jeddah",
  loading: "Loading...",
  itemNotFound: "Item not found",
  error: "Error",
  open: "Open",
  manageProjects: "Manage Projects",
  addProject: "Add Project",
  key: "Key",
  nameAr: "Name (Arabic)",
  nameEn: "Name (English)",
  manageSupervisors: "Manage Supervisors",
  addSupervisor: "Add Supervisor",
  editSupervisor: "Edit Supervisor",
  passwordRequired: "Password is required",
  leaveBlankToKeep: "Leave blank to keep current password",
  passwordMismatch: "Passwords do not match",
  deleteProjectConfirm: "Are you sure you want to delete project",
  deleteSupervisorConfirm: "Are you sure you want to delete supervisor",
  projectsAndSupervisors: "Projects & Supervisors",
  editPermit: "Edit Permit",
  addPermit: "Add Permit",
  closingNotesRate: "Closing Notes Rate",
  close: "Close",
  daysNoIncident: "Days Without Incident",
  trainingAttend: "Training Attendance",
  noDescription: "No Description",
  actionTaken: "Action Taken",
  noteTitle: "Note Title",
  noteDescription: "Note Description",
  incidentsTitle: "Incident Title",
  incidentsLocation: "Incident Location",
  incidentsSupervisor: "Injured Name",
  allSeverity: "All Severities",
  editIncident: "Edit Incident",
  addIncident: "Add Incident",
  exportOptions: "Export Options",
  selectProjectForExport: "Select Project for Export",
  exportTypeNote: "Exporting as",
  export: "Export",
  print: "Print",
  allTime: "All Time",
  daily: "Daily",
  weekly: "Weekly",
  monthly: "Monthly",
  yearly: "Yearly",
};
